### ISSUE TITLE
code not run properly 

### ISSUE THREAD

**Issue by lakshman1980** [AdityaDaw/FlatTrade#3]
i run this code but the error came like this=  sid  {'RedirectURL': '', 'emsg': 'Something went wrong.. please try after sometime.'} --------------------------------------------------------------------------- KeyError                                  Traceback (most recent call last) Cell In[15], line 14      12 print(reqcodeRes)      13 parsed = urlparse(reqcodeRes['RedirectURL']) ---> 14 reqCode = parse_qs(parsed.query)['Code'][0]      15 api_secret =APIKEY+ reqCode + secretKey      16 api_secret =  hashlib.sha256(api_secret.encode()).hexdigest()  KeyError: 'Code'   how can i resolve it

**Comment by AdityaDaw** [comment]
Hi Lakshman This code actually I am not sure is working properly or not, but I have a code which can connect to FlatTrade account and do the trading automatically.

But Still as a friend I can suggest you doing automatic trading will not help you earn more money.

Do you have proper strategies of algo trading then I can share the real working code with you

**Comment by AdityaDaw** [comment]
See this repo this is working properly, but please the strategy you have to choose wisely otherwise it is not gonna help you, as it has not helped me also.

https://github.com/AdityaDaw/FlatTrade-API-Calling
